dist: xenial
sudo: required
language: java

env:
  global:
    - SONATYPE_USERNAME=ph@phloc.com
    - secure: "JaLSb3fwHUgWyYe/tz0pkkWsJ/y8Iyi8yPSvGEUPW8XqTcmWZGk/oNo+KYCsxOHNmbOjqB23Ehx2jY+X18aI4uyozA28djy1H45FDGTEwx5w5aTm3J+V8pZ0Fi979qa
R76I6QqOyhjp34+kidG/+o+aLH1S5Va7i2PKBVD/1yMKYebYJwOJB8pBocx5X3nmtcwdb+LvwgOSu+Xm69cMdkgxMGjjzyMe2WWY2bgYgdsG/07sW13MvQJumQBu3ngpJKPYQ0F2su
5CIH8QUcQr2/ObA6a2qL/XwqqmRPOnva/ls/HRV9dCYsfkwTJ+fG67Z1kGU2sBtA9+Q94VtG/hPx8dob72jF156gm7VQiUVeARnNt9V0KU6w9nr8fpgLMsUw/niuofEpHR51fvqXB2
+iPugMlFiWzLk6pMmRyO5+1HsVESylFzLCkOUZEkkzdEfCRfKrfLsze1DBIfXN5eOqXXJ4PKgHedr89VsPDlCU9eFwTyKLfq2geHX/bE7niQWMFt16EDWTA3ow48kVONiMbeeQaWw1
vt3WiVehXpo01byfT+Q5c9+8fMkTnpC7TIQoQ8E39GMrrm4jaqG2VIUiD2bVtSyeDh3oLbhMAumXkH4pmjintQOZQrk/hWWLpxTN3HS+iQZWM4yboaCkKllc6UtEwTo7dGEYqtM0dc
Ya0k="

addons:
  sonarcloud:
    organization: "phax-github"
    token:
      secure: "cbupGs0HS3osBbCBzzFp3denCwIcUTBiAFDgtZw2F8ZTKuwS/UnJqR9egDV/dp3GOdXePa7WgHtBl9Ivb5bsHjDOE88v9AhJ/OEiTffGAGQYGFhavtXz7KcucxMLJ7/
xzPeDJQNI+4OwauK6VMDvBYM1ZLvgUdR1xOdMm3iMkkjdpDNHbz4ZBNAcwqHcEpwD4sYP/OSfhii3YK6tVgH7+3YsLOR15PrkruDAkkY7JYDNO2If+7UvCdtV34TnYr1fI6Zpyy55U
cK9nTfJqh8H2wtY2PCSUJmUN8x9Yx0p0wVsuPSDFdL50d88Xb3M2nQreOlykCmC3xwml19CjI3ppx+NsZOh8a5WwH5vk8khrKNZfhwnnTpKG75+6q3PeqGPpsONli6grgBEo36zbQf
Z6J2DLwdCDyJXpUyWO8ohpfZYloTMf0Z9PSSwjTv3EShLm6XgubNL7JJpAdAm3cnwF14TJwLTBLkUBCnLWNxRxsNrwot8L+wFlRNqsEuzjDNIXsyvyuf+nA2NbRIdgtb1ZeVeX/bx5
JFY6Qscjw2PyFaLPTIAH73qcMGWS3npJ6t99B/UH1WHMv75LaUD1gXYhjoZxOezQeL43o8B7+QGBGZHbt+LbtPRbF5md7Y4HIFFxP331oDqtDNJ45sQGL+ltgSEBBd6tM0Icp8w6Gl
r/OI="

install:
#  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U -P jdeps
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U
  
cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - master

jobs:
  include:
    - stage: test
      jdk: openjdk8
      script:
        - mvn test -B -P coverage sonar:sonar
      after_success:
        - mvn deploy --settings travis-settings.xml -DskipTests=true -B -P travis-deploy
        - bash <(curl -s https://codecov.io/bash)
    - stage: test
      jdk: openjdk11
      script:
        - mvn test -B
    - stage: test
      jdk: openjdk14
      script:
        - mvn test -B
